style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/edispark/terraform-ecs-container-instance-draining
options:
  allow_uncategorized: false
  commits:
    filters:
      Type:
        - fix
        - feat
        - build
        - chore
        - ci
        - docs
        - style
        - refactor
        - perf
        - test
        - revert
  commit_groups:
    # Taken From: https://github.com/pvdlg/conventional-changelog-metahub
    title_maps:
      fix: ğŸ› Bug Fixes
      feat: âœ¨ Features
      build: ğŸ›  Builds
      chore: â™»ï¸ Chores
      ci: âš™ï¸ Continuous Integrations
      docs: ğŸ“š Documentation
      style: ğŸ’ Styles
      refactor: ğŸ“¦ Code Refactoring
      perf: ğŸš€ Performance Improvements
      test: ğŸš¨ Tests
      revert: ğŸ—‘ Reverts
  header:
    pattern: '^(\w*)(?:\(([\w\$\.\-\*\s]*)\))?\:\s(.*)$'
    pattern_maps:
      - Type
      - Scope
      - Subject
